spring:  
  profiles:
    active: dev
server:
  port: 8011

logging:
  level:
    '[com.backend.challenge]':  DEBUG

management:
  endpoints:
    web:
      exposure:
        include:
        - health
        - info
        - metrics

---
spring:
    profiles: dev
    datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://zemoga-test-db.crhpedy9xxto.us-east-1.rds.amazonaws.com:3306/zemoga_test_db
      username: zemoga_test_db
      password: Zem0ga.101
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
      show_sql: true
      hibernate:
        ddl-auto: none
      
     
